### ISSUE TITLE
PunktSentenceTokenizer abbrev

### ISSUE THREAD

**Issue by v-nhandt21** [binhvq/news-corpus#1]
Dạ cho em hỏi ở bước PunktSentenceTokenizer abbrev là mình làm gì ạ, em chưa hiểu lắm ạ

**Comment by binhvq** [comment]
This tokenizer divides a text into a list of sentences
by using an unsupervised algorithm to build a model for abbreviation
words, collocations, and words that start sentences.  It must be
trained on a large collection of plaintext in the target language
before it can be used.
