### ISSUE TITLE
Can not download CSV Data

### ISSUE THREAD

**Issue by binhna** [binhvq/news-corpus#2]
Hi Binh,
First of all, thank you for this great work.
I downloaded the `full_text` version and looked at the data, it seems like you put all articles together without an empty line between them. So there is no way to split article.
Therefore, I want to download the CSV version hoping it is article-separable. But couldn't access the link you gave. Could you fix it and update the README or drop a new link here, please? Thanks in advance.

**Comment by binhvq** [comment]
Hi binhna!
My Server is down. It may take 1-2 days for the server to be fix.
Thanks.

**Comment by binhna** [comment]
It works like a charm now. Thanks

**Comment by autobotasia** [comment]
It seems to it is down now. Can you please help to take a look @binhvq 
@binhna: Does CSV version is article-separable?
