### ISSUE TITLE
Cannot download CSV file

### ISSUE THREAD

**Issue by anhhuy0501** [binhvq/news-corpus#4]
Hi @binhvq 
Thank you very much for your great work.

I cannot download the CSV file, could you fix the link?

CSV V2
Size: 5.6GB, Uncompress ~49GB Download: [http://103.140.38.25/corpus/corpus-cate-csv-2019-24-03.7z](url)

Thanks in advance.

**Comment by binhvq** [comment]
Please try again, if u can't download, try again after some days.
