### ISSUE TITLE
Cập nhật bộ dữ liệu news-corpus

### ISSUE THREAD

**Issue by Luvata** [binhvq/news-corpus#5]
Em muốn hỏi là sắp tới anh có kế hoạch update bộ dữ liệu này không ạ? Em đang thấy bộ dữ liệu news-corpus hiện tại là dump đến 2018/12/17 chưa có các thông tin về Covid19, về tổng thống Mỹ mới, ...

Cảm ơn anh Bình và team đã public bộ dữ liệu này cho cộng đồng.

**Comment by binhvq** [comment]
Chào bạn, dữ liệu hiện tại đã lên đến 18 triệu bài viết. Mình sẽ export và share trong thời gian sớm nhất.
Cảm ơn bạn đã quan tâm.

**Comment by Luvata** [comment]
Cảm ơn anh và team đã chia sẻ ạ !

**Comment by Luvata** [comment]
Em thấy anh vừa commit cập nhật thêm link dump 20M news đến ngày 21/05/2021 rồi ạ
Cảm ơn anh và team nhiều ạ 💯
