### ISSUE TITLE
Lỗi server 103.140.38.25

### ISSUE THREAD

**Issue by Luvata** [binhvq/news-corpus#6]
Sorry anh, có phải server đang down không ạ? Từ hôm qua (12/06/2021) em không còn tải được data từ domain `103.140.38.25`

![210613152204](https://user-images.githubusercontent.com/17178612/121800265-23399a80-cc5b-11eb-925d-010796429c8b.png)

Anh kiểm tra giúp em với ạ, cảm ơn anh nhiều ạ

**Comment by binhvq** [comment]
Please Try again!

**Comment by Luvata** [comment]
You are so efficient. Thank you so much!

**Comment by nguyenthanhquang152** [comment]
@binhvq Mình mới kiểm tra thì domain vẫn down nha bạn.

**Comment by Luvata** [comment]
Hi @nguyenthanhquang152 , nếu bạn tải version 21/05/2021 thì mình có tạo replicate tại link này [huggingface's dataset](https://huggingface.co/datasets/imthanhlv/binhvq_news21_raw/tree/main). Các corpus khác nếu có thời gian mình sẽ backup sang HF datasets
