### ISSUE TITLE
Link tới TXT V2 bị hỏng

### ISSUE THREAD

**Issue by tiendung** [binhvq/news-corpus#7]
Full TXT V2
Kich thuoc: 5GB, Uncomress ~27.5GB Download: http://103.140.38.25/corpus/corpus-full-20181217.7z?fbclid=IwAR1JVzoxe-Q4pZAwm7w9rswdeTNeB_gpecB-Pze13dvLDNtYWI4lQKkGsjI

Tôi download ko dc, bạn có thể sửa dc ko?

**Comment by binhvq** [comment]
Mình vừa check link vẫn bình thường nhé.

**Comment by nguyenthanhquang152** [comment]
Domain vẫn bị down nhé @binhvq
