### ISSUE TITLE
Script chuẩn hóa demo-full.txt

### ISSUE THREAD

**Issue by Luvata** [binhvq/news-corpus#8]
Anh có thể public source code chuẩn hóa để tạo file có format như `demo-full.txt` không ạ ? 
Em đang chuẩn hóa bộ dữ liệu 21/05 và muốn reproduce lại pipeline chuẩn hóa cũ và có thể cải thiện thêm.
Em cảm ơn anh nhiều ạ.

**Comment by Luvata** [comment]
Em đang sử dụng Beautifulsoup để lấy các paragraph, chi tiết về clean em sẽ cập nhật thêm trong các comment sau. Cảm ơn anh và team đã public bộ dữ liệu này ạ

**Comment by tranmanhdat** [comment]
@Luvata không biết bạn đã chuẩn hóa được chưa, có thể chia sẻ được không?

**Comment by Luvata** [comment]
@tranmanhdat check this out https://huggingface.co/datasets/imthanhlv/binhvq_dedup

**Comment by tranmanhdat** [comment]
@Luvata thank for sharing entire processed dataset, but can i get source code to adapt some preprocessing on text?
